---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-ctr
  labels:
    app: nginx-ctr
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-ctr
  template:
    metadata:
      labels:
        app: nginx-ctr
    spec:
      containers:
      - name: nginx-ctr
        image: nginx:1.15.4
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc-ctr
  labels:
    app: nginx-ctr
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: nginx-tcp
