apiVersion: v1
kind: Pod
metadata:
  name: podb
  labels:
    app: python
    role: vote
    version: v1
spec:
  containers:
    - name: app
      image: schoolofdevops/vote:v1
      resources:
        limits:
          cpu: "20"
          memory: "64Mi"
